### ISSUE TITLE
Ignore dirs based on .gitignore

### ISSUE THREAD

**Issue by narbehaj** [narbehaj/bash-backup#1]
Add a feature to ignore directories if there is .gitignore

**Comment by vahit** [comment]
اوّل بگم که اسکریپت خوبیه و جای بهتر شدن هم داره و می‌شه خیلی خوب توسعه‌ش داد.
‫در مورد این gitignore هم به نظر من لازم نیست آپشنالش کرد چون کلاً نیازی به بک‌آپ گرفتن از ignore شده‌ها نمی‌بینم.
‫و اینکه آقای خزری گفتن شاید git init نشده یه خورده ماجرا رو سخت‌تر می‌کنه، یعنی ما بخوایم برای خود اسکرپیت یه آپشن exclude ایجاد کنیم. سخت نیست ولی خب رفته رفته اسکرپیت رو پیچیده‌تر می‌کنن. شاید آخرش به جایی برسه که کسی به خاطر پیچیدگیش تمایلی به استفاده ازش نداشته باشه. مثل بقیه‌ی اسکریپت‌ها و برنامه‌های بک‌آپ‌گیری موجود

**Comment by vahit** [comment]
‫البته الان که دارم بیشتر فکر می‌کنم همون شرط چک کردن دایرکتوری git رو حذف کنیم هر کی خواست داخل ‫دایرکتوریش یه‪ .gitignore‬ بسازه برای exclude کردن.
